language: android
jdk: oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
android:
 licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
before_script:
    # Prepare pre-accepted licenses to not be promted at installation
   - mkdir "$ANDROID_HOME/licenses" || true
   - cp ./licenses/* "$ANDROID_HOME/licenses/"
before_install:
    - yes | sdkmanager "platforms;android-28"
    - chmod +x gradlew
script:
    - ./gradlew build check
